title: Carlos Andres Bolaños R.A
description: TECHNOLOGY, PROGRAMMING, THOUGHTS AND OTHER ESSENTIALS.

url: http://cabol.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: cabol
   twitter: candresbolanos
   email: cabol.dev@gmail.com

google_analytics: "UA-58263416-1"
