# Site settings
title: Carlos Andres Bolaños Blog.
email: cabol.dev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  TECHNOLOGY, PROGRAMMING, THOUGHTS AND OTHER ESSENTIALS.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cabol.github.io"
twitter_username: candresbolanos
github_username:  cabol

# Build settings
markdown: kramdown
