# Site settings
title: 'Carlos Andres Bola単os'
email: 'candres.bolanos@gmail.com'
description: 'TECHNOLOGY, PROGRAMMING, THOUGHTS AND OTHER ESSENTIALS.'
url: 'http://cabol.github.io'
baseurl: ''

author:
  name     : 'Carlos Andres Bola単os'
  email    : 'candres.bolanos@gmail.com'
  url      : http://sakurapps.com
  twitter  : http://twitter.com/candresbolanos
  linkedin : http://linkedin.com/in/cabolanos
  github   : http://github.com/cabol

disqus: true
disqus_shortname: cabolanos

paginate: 4
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown

# Exclude these files from your production _site
exclude:
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - README.md
  - INSTALL.md

# Default Settings
defaults:
  -
    scope:
      path: ''        # an empty string here means all files in the project
      type: 'pages'
    values:
      layout: page      # Set default layout to page
      show_meta: false  # Hide metadata for all pages
      comments: false
      author: 'Carlos Andres Bola単os'     # Default author for pages
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: page      # Set default layout to page
      show_meta: true   # Show metadata for all posts
      comments: false
      author: 'Carlos Andres Bola単os'     # Default author for posts

# social footer
social:
  github:
    slug: github
    link: http://github.com/cabol
  twitter:
    slug: twitter
    link: http://twitter.com/candresbolanos
  linkedin:
    slug: linkedin
    link: http://linkedin.com/in/cabolanos
