# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Site settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- demo/*
- alembic-jekyll-theme.gemspec

# 2. Installed Gems
gems:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jemoji

# 3. Site settings
encoding: utf-8 # Make sure the encoding is right
title: 'Carlos Andres Bolaños'
email: 'candres.bolanos@gmail.com'
description: 'TECHNOLOGY, PROGRAMMING, THOUGHTS AND OTHER ESSENTIALS.'
url: 'http://cabol.github.io'
baseurl: ''

author:
  name     : 'Carlos Andres Bolaños'
  email    : 'candres.bolanos@gmail.com'
  url      : http://sakurapps.com
  twitter  : http://twitter.com/candresbolanos
  linkedin : http://linkedin.com/in/cabolanos
  github   : http://github.com/cabol

twitter:
  username: candresbolanos

social:
  github:
    slug: github
    link: http://github.com/cabol
  twitter:
    slug: twitter
    link: http://twitter.com/candresbolanos
  linkedin:
    slug: linkedin
    link: http://linkedin.com/in/cabolanos

disqus: true
disqus_shortname: cabolanos

paginate: 4
comments: true
#paginate_path: "/page/:num"
paginate_path: blog/page:num

logo: "/assets/logo.svg" # Site logo, also used in jekyll-seo-tag
avatarurl: "/images/avatar.jpg"

# 4. Jekyll settings
sass:
  style: compressed # Style compression
  sass_dir: _sass
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "TECHNOLOGY, PROGRAMMING, THOUGHTS AND OTHER ESSENTIALS." # The post list page content
    feature_text: |
      Welcome to my blog
    feature_image: "https://unsplash.it/1300/400?image=881"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page # Default layout
      image: "/assets/default-social-image.png" # Default image for sharing
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post # Default layout
      image: "/assets/default-social-image.png" # Default image for sharing

# 8. Site navigation
navigation_header:
  Home: /
  Blog: /blog/
  Categories: /categories/
  Search: /search/

navigation_footer:
  Made with Jekyll using alembic theme: https://alembic.darn.es

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/candresbolanos
  LinkedIn: https://www.linkedin.com/in/cabolanos
  Google+: https://plus.google.com/u/1/101773583932530426614
  GitHub: https://github.com/cabol
  link: https://cabol.github.io
  RSS: /feed.xml
