# Site settings
title: Carlos Andres Bolaños R.A
email: candres.bolanos@gmail.com
description: TECHNOLOGY, PROGRAMMING, THOUGHTS AND OTHER ESSENTIALS.
url: http://cabol.github.io
baseurl: ""

twitter_username:  candresbolanos
github_username:   cabol
linkedin_username: cabolanos

disqus: true
disqus_shortname: cabolanos

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
#timezone:    America/Bogota
#future:      true
#highlighter: pygments

# Build settings
markdown: kramdown

exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
